[package]
name = "viaems"
version = "0.1.0"
edition = "2024"

[dependencies]
viaems-interface-derive = { path = "../viaems-interface-derive" }
clap = { version = "4.4", features = ["derive"] }
duckdb = { version = "1.4", features = ["bundled"] }
nusb = "0.2"
futures-lite = "2.6"
ctrlc = "3.4"
network-interface = "2"
prost = "0.14.3"
cobs = "0.5.0"
crc = "3.4.0"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
prost-build = "0.14.3"
