[package]
name = "viaems-ui"
version = "0.1.0"
authors = [""]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.72"
publish = false

[dependencies]
egui = "0.31"
eframe = { version = "0.31", features=["wgpu", "wayland"]}
emath = { version = "0.31" }
epaint = "0.31"
egui_file = "0.22"
clap = { version = "4.4.12", features = ["derive"] }

viaems = { path = "../viaems" }
env_logger = "*"
